version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: fitness-lms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fitness_admin_2024
      MYSQL_DATABASE: fitness_lms
      MYSQL_USER: fitness_user
      MYSQL_PASSWORD: fitness_pass_2024
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fitness_network
    command: --default-authentication-plugin=mysql_native_password

  # phpMyAdmin (Web interface for MySQL)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fitness-lms-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: fitness_admin_2024
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - fitness_network

volumes:
  mysql_data:

networks:
  fitness_network:
    driver: bridge